### ISSUE TITLE
goroutine error 

### ISSUE THREAD

**Issue by todayisnew369** [gwen001/github-endpoints#4]
goroutine 1 [running]:
main.getNextToken(0x6cd5de?, 0x5?)

        /go/pkg/mod/github.com/gwen001/github-endpoints@v0.0.0-20220929102440-32efa730c303/main.go:441 +0x16c
main.main()
        /go/pkg/mod/github.com/gwen001/github-endpoints@v0.0.0-20220929102440-32efa730c303/main.go:567 +0xdeb

**Comment by gwen001** [comment]
More information please. What command did you use, any screenshot ?
